### ISSUE TITLE
NumericAxis issues with values that are float and have 3 zero decimals after floating point

### ISSUE THREAD

**Issue by LugonjaAleksandar** [syncfusion/flutter-examples#19]
In my app case I work with presenting crypto currencies and their value has different ranges. For Bitcoin ranges are around 9000, but for other currencies it gets to 0.000xxxxx. 

When setting data points with values all starting with float 0.000xxxx NumericAxis losses data. I am passing graph info data with 9 digits precision and only leading 3 are zeros, so there should be no problem displaying this, but library doesn't support lower values it seems. Also format displaying in a popup on click shows only "0.0" value, and not floating point values that are passed to the lib. 

Any advice how I can work around the issue and display correct graph data on click, and present correct primaryYAxis? 
You can find attached screenshot from the device, to see what the problem is.
<img width="311" alt="Screen Shot 2019-09-03 at 3 56 03 PM" src="https://user-images.githubusercontent.com/41632269/64179407-6a2e1580-ce63-11e9-863c-1cb9e6840128.png">

**Comment by dharanidharandharmasivam** [comment]
Hi @LugonjaAleksandar ,

Thanks for using our Syncfusion Chart Flutter widget. You can find the response to your queries below.

**Query 1:**  When setting data points with values all starting with float 0.000xxxx NumericAxis losses data.

We have ensured your case by specifying the data with values starting with float 0.000xxxx. Unfortunately, the issue is not replicated at our end. The ranges for the axis is calculated properly based on the given data. 

We have attached a [sample](https://www.syncfusion.com/downloads/support/directtrac/247263/ze/sample209639348) for your reference. Since the reported scenario is not replicated at our end, kindly revert us by modifying the attached sample or share your code with your data source. This will be helpful in resolving the issue earlier.

**Query 2:** Also, format displaying in a popup on click shows only "0.0" value, and not floating-point values that are passed to the lib
We can replicate the reported issue at our end, so we have logged bug reported in our feedback portal. You can track the status of the bug from our below link.

[Feedback Link](https://www.syncfusion.com/feedback/8752)

Also, as a workaround using the **onTooltipRender** event, you can customize the text displayed in the tooltip. We have shown the x and y values in the tooltip. You can customize this based on your requirements. 


`SfCartesianChart(
          onTooltipRender: (TooltipArgs args) {
            final DateFormat format = DateFormat.Hm();
            args.text = "XValue : " + format.format(args.dataPoints[args.pointIndex].x).toString() +
                " YValue : " + args.dataPoints[args.pointIndex].y.toString();
          },
        )
`

We will fix the bug and we will include in our upcoming update. We appreciate your patience until then.

Thanks,
Dharani.

**Comment by LugonjaAleksandar** [comment]
Hi Dharani, 

Your sample code provided values above 0.000xxxx and that is why it shows all values. Just tried your example and removed values above this limit, and it exactly shows my problem. Replace example data set with this and watch what happens: 

    dataSource: [
                  ChartData(DateTime(2019,1,1,1,23), 0.000234527),
                  ChartData(DateTime(2019,1,1,2,32), 0.000344574),
                  ChartData(DateTime(2019,1,1,2, 50), 0.000544526),
                  ChartData(DateTime(2019,1,1, 3, 32), 0.000387527),
                  ChartData(DateTime(2019,1,1,4, 37), 0.000194523),
                  ChartData(DateTime(2019,1,1, 5, 32), 0.000384265),
                  ChartData(DateTime(2019,1,1, 6, 19), 0.000852943),
                  ChartData(DateTime(2019,1,1, 7, 20), 0.000234567),
                  ChartData(DateTime(2019,1,1, 8, 43), 0.000921029),
                  ChartData(DateTime(2019,1,1, 9, 32), 0.000234561),
                  ChartData(DateTime(2019,1,1, 10, 43), 0.000289101),
                  ChartData(DateTime(2019,1,1,14, 29), 0.000323982),
                  ChartData(DateTime(2019,1,1, 19,29), 0.000763289),
                  ChartData(DateTime(2019,1,1, 20,27), 0.000923982),
                  
                ],

**Comment by JayavigneshwaranG** [comment]
Hi @LugonjaAleksandar ,

Thanks for your patience.
Now we have fixed the reported issues and published to pub. So we request you to use the [latest version packages(1.0.0-beta.5)](https://pub.dev/packages/syncfusion_flutter_charts/versions/1.0.0-beta.5). Now the axis interval is calculated properly for small decimal values. Also by default 3 decimal places will be displayed in the tooltip text. Now we have introduced a new property ‘**roundingPlace**’ in tooltipBehavior. You can specify the desired value to this property. For example, if you specify 5, 5 decimal places will be displayed (0.00001). But if you specify 3, then the value will be rounded off and 0.0 alone will be displayed instead of 0.000. 

We are closing this issue. You can reopen this if you face any concerns.

Thanks,
Jayavigneshwaran

**Comment by LugonjaAleksandar** [comment]
Specific issue is fixed, that is true, but now you made another one forcing latest library of intl: 0.16.0 to be used. Is this really necessary to do here? That made this lib incompatible with other libs that are also dependent on "intl" such as "local_auth" but that one is not ready to enforce 1.16.0. I guess relaxing dependency should fix the compatibility issue.

**Comment by dharanidharandharmasivam** [comment]
Hi @LugonjaAleksandar ,

We have analyzed your scenario. Pub recommends using the latest version of dependency packages. If we are not using the latest version dependent libraries, then while publishing our package in the pub, it will show the below message and reduce the scoring.
 
[Pub Image](https://www.syncfusion.com/downloads/support/directtrac/general/pubImage-1006178990)
 
To avoid this, we need to upgrade the dependent libraries. To overcome the reported scenario locally, the chart library which you are using will be stored in your local machine. You can change the intl package version in the chart’s pubspec.yaml file manually in your machine else you can request the libraries to upgrade to the latest version.

Thanks,
Dharani.

**Comment by LugonjaAleksandar** [comment]
Hi guys, we still have this issue and it is related to testing framework given by flutter that still uses intl: ^0.15.8. You need to be compliant with latest "stable" flutter branch since that is what developers use. And in this case their own framework (flutter_driver) uses lower version and outputs errors when I increase version of intl to 1.16.0. Can you pleeease do something about it? There is no way for us to move forward with the framework and subscription for Flutter on this framework if it is not supported in our app at the moment.
