### ISSUE TITLE
Error when install syncfusion_flutter_calendar ver 19.1.65

### ISSUE THREAD

**Issue by TeaHee** [syncfusion/flutter-examples#361]
When i install syncfusion_flutter_calendar ver 19.1.65, i have a error like the image. How to fix it. Thank you
![Capture](https://user-images.githubusercontent.com/48523997/120260797-c506d200-c2c0-11eb-8c94-841a6696728d.JPG)

**Comment by Indumathi1195R** [comment]
Hi,

Based on the shared information, we have checked the mentioned issue “**Error occurred while installing the calendar package version 19.1.65**”. We are unable to reproduce the mentioned issue from our end and it is working fine as expected. We have attached the tested image for the same. 

**Screenshot:**
 
![Screenshot (158)](https://user-images.githubusercontent.com/54974849/120301136-30b16500-c2ea-11eb-910b-c2a861ab014a.png)

We have fixed this issue in our Flutter Calendar package version 18.1.46-beta. Please find the changelog for the same.

**Changelog link:**
https://pub.dev/packages/syncfusion_flutter_calendar/changelog

If possible, can you please run the flutter clean command and run the sample. If still, you are facing the same issue, can you please share the below details with us, it would be helpful for us to analyze and provide you a solution at the earliest?

•	Code snippet related to calendar
•	Code snippet of the Pubspec.yaml file

Regards,
Indumathi R

**Comment by TeaHee** [comment]
Hi, after I run the flutter clean command and run the sample. It still the same issue.

So this is my Code snippet of the Pubspec.yaml file:
![Untitled](https://user-images.githubusercontent.com/48523997/120410760-d06c0300-c37d-11eb-9934-e40b88124d46.png)

And this is my Code snippet related to calendar:
![Capture1](https://user-images.githubusercontent.com/48523997/120411589-3efd9080-c37f-11eb-98a0-6440353b0367.JPG)
![Capture3](https://user-images.githubusercontent.com/48523997/120411757-871cb300-c37f-11eb-8395-d6ed65fb6f10.JPG)
![Capture2](https://user-images.githubusercontent.com/48523997/120411765-897f0d00-c37f-11eb-8065-c2c00d1e67d4.JPG)

**Comment by Indumathi1195R** [comment]
Hi TeaHee,

Thank you for the update.

Based on the shared code snippet, we have prepared the simple sample with resources and we are unable to reproduce the mentioned time zone-related error from our end. Please find the sample from the following link.

**Sample link:** 
[Sample.zip](https://github.com/syncfusion/flutter-examples/files/6590939/Sample.zip)


If possible, can you please check your project once and let us know if the time zone package was installed or not. We have attached the screenshot for the same.

**Screenshot:**
<img width="672" alt="Screenshot (163)" src="https://user-images.githubusercontent.com/54974849/120630514-8c175a80-c484-11eb-9b54-5e6c5304664c.png">

We hope that this helps you. Please let us know if you need further assistance.

Regards,
Indumathi R

**Comment by TeaHee** [comment]
Hi,

Thanks for your support.

After install lib timezone: ^0.7.0 in pub.dev, I run project normally.

Here is my example:

![image](https://user-images.githubusercontent.com/48523997/120736772-0c869b80-c517-11eb-8195-ae6d506c96bd.png)
